# scripts/precompute_gallery.py
#
# Precomputes all gallery entries.
# Run: python scripts/precompute_gallery.py
#
# Required env vars: DATABASE_URL, S2_API_KEY, NLP_WORKER_URL, NLP_WORKER_SECRET,
#                    R2_ACCOUNT_ID, R2_BUCKET_NAME, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY,
#                    GROQ_API_KEY (optional, for genealogy text)
#
# Output:
#   - Full graph JSON uploaded to R2 at: precomputed/<slug>/graph.json
#   - Preview graph JSON (top 20 nodes) at: precomputed/<slug>/preview.json
#   - Mini graph SVG at: precomputed/<slug>/preview.svg
#   - Genealogy text at: precomputed/<slug>/genealogy.md
#   - gallery_index.json updated with final stats

import sys
import os
import json
import time
import asyncio
import argparse
import logging
import math
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

from backend.config import config
from backend.graph_engine import AncestryGraph
from backend.dna_profiler import DNAProfiler
from backend.diversity_scorer import DiversityScorer
from backend.r2_client import R2Client
from backend.db import init_pool

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
logger = logging.getLogger(__name__)

GALLERY_PAPERS = [
    {"slug": "attention", "paper_id": "204e3073870fae3d05bcbc2f6a8e263d9b72e776"},
    {"slug": "alexnet",   "paper_id": "abd1c342495432171beb7ca8fd9551ef13cbd0ff"},
    {"slug": "bert",      "paper_id": "df2b0e26d0599ce3e70df8a9da02e51594e0e992"},
    {"slug": "gans",      "paper_id": "54e325aee6b2d476bbbb88615ac15e251c6e8214"},
    {"slug": "word2vec",  "paper_id": "330da625c15427c6e42ccfa3b747fb29e5835bf0"},
    {"slug": "resnet",    "paper_id": "2c03df8b48bf3fa39054345bafabfeff15bfd11d"},
    {"slug": "gpt2",      "paper_id": "9405cc0d6169988371b2755e573cc28650d14dfe"},
]


def precompute_paper(slug: str, paper_id: str, r2: R2Client,
                     force: bool = False) -> dict:
    """
    Build and store all precomputed data for one gallery paper.
    Returns stats dict for gallery_index.json.
    """
    logger.info(f"Processing {slug} ({paper_id})...")

    # Skip if already computed (unless --force)
    if not force and r2.exists(f"precomputed/{slug}/graph.json"):
        logger.info(f"  {slug} already precomputed, skipping (use --force to recompute)")
        existing = r2.get_json(f"precomputed/{slug}/graph.json")
        return existing.get('metadata', {}) if existing else {}

    # 1. Build graph (Phase 4 backport §0.8: correct method name + signature)
    graph = AncestryGraph()
    start = time.time()
    asyncio.run(graph.build_graph(paper_id))
    build_time = time.time() - start
    logger.info(f"  Graph built in {build_time:.1f}s: {len(graph.nodes)} nodes")

    # 2. Export full graph JSON
    graph_json = graph.export_to_json()

    # 3. Add precomputed pruning for the seed paper (needed for landing demo)
    from backend.pruning import compute_pruning_result, compute_all_pruning_impacts
    seed_pruning = compute_pruning_result(
        graph.graph, [paper_id], graph.nodes, graph.seed_paper_id
    )
    graph_json['precomputed_pruning'] = {paper_id: seed_pruning.to_dict()}

    # 4. Add precomputed leaderboard (top 10)
    all_impacts = compute_all_pruning_impacts(graph.graph)
    graph_json['leaderboard'] = sorted(
        [{'paper_id': pid, **data} for pid, data in all_impacts.items()],
        key=lambda x: x['collapse_count'], reverse=True
    )[:10]

    # 5. DNA profile
    dna_profiler = DNAProfiler()
    paper_ids = list(graph.nodes.keys())
    dna = dna_profiler.compute_profile(paper_ids, graph.seed_paper_id, graph.nodes)
    graph_json['dna_profile'] = dna.to_dict() if hasattr(dna, 'to_dict') else dna

    # 6. Diversity score
    diversity = DiversityScorer().compute_score(paper_ids, graph.nodes)
    graph_json['diversity_score'] = diversity.to_dict() if hasattr(diversity, 'to_dict') else diversity

    # 7. Initial insights (first 3, for Insight Feed)
    graph_json['initial_insights'] = []  # Generated by LLM in build phase

    # 8. Upload full graph
    r2.put_json(f"precomputed/{slug}/graph.json", graph_json)
    logger.info(f"  Full graph uploaded to R2")

    # 9. Build preview graph (top 20 nodes by citation count)
    top_nodes = sorted(graph_json['nodes'], key=lambda n: n.get('citation_count', 0), reverse=True)[:20]
    top_node_ids = {n['id'] for n in top_nodes}
    preview = {
        'nodes': top_nodes,
        'edges': [e for e in graph_json['edges']
                  if e['source'] in top_node_ids and e['target'] in top_node_ids],
        'metadata': graph_json['metadata']
    }
    r2.put_json(f"precomputed/{slug}/preview.json", preview)
    logger.info(f"  Preview graph uploaded")

    # 10. Generate mini SVG preview
    mini_svg = generate_mini_svg(preview)
    r2.put(f"precomputed/{slug}/preview.svg", mini_svg.encode('utf-8'), 'image/svg+xml')
    logger.info(f"  Mini SVG uploaded")

    # 11. Generate genealogy text (requires GROQ_API_KEY)
    # Phase 4 backport §0.8: generate_genealogy_story() is sync, not async
    if config.GROQ_ENABLED:
        from backend.llm_client import ArivuLLMClient
        llm = ArivuLLMClient()
        genealogy_result = llm.generate_genealogy_story(graph_json)
        genealogy_text = genealogy_result.get('narrative', '') if isinstance(genealogy_result, dict) else str(genealogy_result)
        r2.put_text(f"precomputed/{slug}/genealogy.md", genealogy_text)
        logger.info(f"  Genealogy text uploaded")

    stats = {
        'papers': len(graph_json['nodes']),
        'edges': len(graph_json['edges']),
        'fields': len(set(f for n in graph_json['nodes'] for f in n.get('fields_of_study', []))),
        'depth': 2,
        'build_time_seconds': round(build_time, 1)
    }

    # Phase 4 backport §0.8: write stats back to gallery_index.json
    import pathlib
    _gallery_path = pathlib.Path("data/gallery_index.json")
    if _gallery_path.exists():
        try:
            _gallery = json.loads(_gallery_path.read_text())
            for _entry in _gallery:
                if _entry.get("slug") == slug:
                    _entry.setdefault("stats", {}).update({
                        "papers": stats["papers"],
                        "edges": stats["edges"],
                    })
            _gallery_path.write_text(json.dumps(_gallery, indent=2))
            logger.info(f"  gallery_index.json updated for {slug}")
        except Exception as e:
            logger.warning(f"  Failed to update gallery_index.json: {e}")

    logger.info(f"  {slug} complete: {stats}")
    return stats


def generate_mini_svg(preview_graph: dict, width: int = 200, height: int = 150) -> str:
    """Generate a tiny SVG preview of the graph. No external dependencies."""
    nodes = preview_graph['nodes']
    edges = preview_graph['edges']

    if not nodes:
        return f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}"></svg>'

    # Simple circular layout
    positions = {}
    n = len(nodes)
    cx, cy = width / 2, height / 2
    r = min(width, height) * 0.38

    for i, node in enumerate(nodes):
        angle = (2 * math.pi * i / n) - math.pi / 2
        positions[node['id']] = (cx + r * math.cos(angle), cy + r * math.sin(angle))

    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'style="background:#0a0e17">'
    ]

    # Edges
    for edge in edges[:50]:  # Cap at 50 edges for preview
        src = positions.get(edge['source'])
        tgt = positions.get(edge['target'])
        if src and tgt:
            svg_parts.append(
                f'<line x1="{src[0]:.1f}" y1="{src[1]:.1f}" '
                f'x2="{tgt[0]:.1f}" y2="{tgt[1]:.1f}" '
                f'stroke="#475569" stroke-width="0.5" stroke-opacity="0.4"/>'
            )

    # Nodes
    for node in nodes:
        pos = positions.get(node['id'])
        if not pos:
            continue
        size = 1.5 + math.log10(node.get('citation_count', 1) + 1) * 1.2
        color = '#3B82F6' if 'Computer' in str(node.get('fields_of_study', [])) else '#D4A843'
        svg_parts.append(
            f'<circle cx="{pos[0]:.1f}" cy="{pos[1]:.1f}" r="{size:.1f}" '
            f'fill="{color}" opacity="0.8"/>'
        )

    svg_parts.append('</svg>')
    return '\n'.join(svg_parts)


def main():
    parser = argparse.ArgumentParser(description='Precompute Arivu gallery entries')
    parser.add_argument('--slug', help='Only process this slug (e.g., "attention")')
    parser.add_argument('--force', action='store_true', help='Recompute even if already exists')
    args = parser.parse_args()

    # Initialize
    init_pool(config.DATABASE_URL, config.DB_POOL_MIN, config.DB_POOL_MAX)
    r2 = R2Client(config)

    papers_to_process = GALLERY_PAPERS
    if args.slug:
        papers_to_process = [p for p in GALLERY_PAPERS if p['slug'] == args.slug]
        if not papers_to_process:
            logger.error(f"Unknown slug: {args.slug}")
            sys.exit(1)

    results = {}
    for paper in papers_to_process:
        try:
            stats = precompute_paper(paper['slug'], paper['paper_id'], r2, force=args.force)
            results[paper['slug']] = {'status': 'success', 'stats': stats}
        except Exception as e:
            logger.error(f"Failed to precompute {paper['slug']}: {e}", exc_info=True)
            results[paper['slug']] = {'status': 'error', 'error': str(e)}

    # Summary
    logger.info("\n" + "="*50)
    logger.info("PRECOMPUTE SUMMARY")
    for slug, result in results.items():
        status = 'OK' if result['status'] == 'success' else 'FAIL'
        logger.info(f"  {status} {slug}: {result.get('stats', result.get('error', ''))}")


if __name__ == '__main__':
    main()
